name = "testPackage"
uuid = "4b3dfc03-89e5-436a-a2a6-5077d84c1cd0"
authors = ["AlexGotham <aleger567@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
